### PR TITLE
Configure Android App Bundle

### LINKED ISSUE #544: Reduce the size using the Android App Bundle
>Your app could be 60.7% smaller if you used the Android App Bundle. The APKs generated from the app bundle give your users smaller, more optimized downloads. 

>This calculation is based on your latest production release and the XXHDPI ARMv7 device configuration.

https://support.google.com/googleplay/android-developer/answer/9006925

### PR DESCRIPTION
**Pull request by beatbrot**
Fixes #544 

## Testing and Review Notes

I tried to evaluate the benefits of Android App Bundles in this specific usecase. I tested it with an AVD running as a Pixel 2 XL in english language (x86) and my OnePlus One in german language (arm)

|Variant|File Size | Expected Download Size*|
|---|---|---|
|Debug APK|49.1MB|?|
|Debug Bundle (OnePlus One)|47.2MB|18.5MB|
|Debug Bundle (Emulator) | 47.5MB|18.6MB|
|Release APK|41.5MB|?|
|Release Bundle (OnePlus One)|45.9 MB| 17.2MB|
|Release Bundle (Emulator) | 46.2MB | 17.3MB|

*The expected download size was optained by running [bundletool](ff) with the options `get-size total`. The numbers that were returend did not have a unit. But my best guess is, that the unit was bytes. For better readability, I converted them to Megabytes.

The bigger task would be to change how the app is published to Google Play. But I guess this has to be done by someone from the Mozilla Team :)

## To Do

- [ ] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by beatbrot** [comment]
CI will fail until #572 will be merged

**Comment by beatbrot** [comment]
Again, I can't see how my changes could make this test fail....

**Comment by sashei** [comment]
Hi @beatbrot, apologies for the delay on this PR. We are still deciding about having an in-app language picker rather than using the device-level language setting, obviating the need for this particular improvement at this time. Thank you for stepping in here, and we welcome further contributions!!

**Comment by beatbrot** [comment]
@sashei No problem! :) Maybe you can even make use of my research for your decision!

**Pull request closed without merging**
