### PR TITLE
Fix race condition in LocketPresenterTest and make it non-flaky

### LINKED ISSUE #508: Merge `RoutePresenter ` and `AutofillRoutePresenter`
Requires #499

### PR DESCRIPTION
**Pull request by beatbrot**
Fixes #539
Fixes #572 

## Testing and Review Notes

By moving the mocks up, the race condition can be resolved. Otherwise it would be possible, that the mocking would not be completed when the events are emitted.

## Personal note

Wow...Fixing this was quite a bit of work, but I finally got it! Also I learned quite a bit of RxJava on the way so I guess it was worth it. I hope you are happy with the patch!

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by beatbrot** [comment]
Well it doesnt work tough :/

**Comment by eliserichards** [comment]
🤔 this looks good to me. What makes you say it doesn't work? I think it's ready for merging.

**Comment by beatbrot** [comment]
I think it is still not fixed because [this build](https://app.bitrise.io/build/036c3d166fd35c59) still failed and I did not make any substantial changes after the commit that caused the build. Maybe this PR is a first step because it fixed flakyness on my machine, but bitrise still seems flaky.

**Comment by devinreams** [comment]
>this build still failed and I did not make any substantial changes after the commit that caused the build

Bitrise has been a bit flakey the past few days and times-out during debug unit test steps which is what happened on that first build (ran for ~90 minutes stuck on the test step).

To @eliserichards's point, I agree, we can merge this as the testing timeout seems unrelated to this test refactor, specifically. :shipit:

**Comment by devinreams** [comment]
Thank you for your contributions, @beatbrot 🙇

**Pull request merged**
