### PR TITLE
Update Android Studio and kotlin and gradle

### PR DESCRIPTION
**Pull request by devinreams**
I don't think this will build successfully, there should be errors.

### CODE REVIEW

**Comment by devinreams** [comment]
OK this should be working.

@sashei @jhugman @linuxwolf Do you want to / are you ready to update to Android Studio 3.2 and these other things?

I dropped updating android-components here because of additional logins mocking needed...

**Comment by sashei** [comment]
@devinreams ready!!

**Comment by jhugman** [comment]
I'm ready here.

**Comment by devinreams** [comment]
Thanks, here we go to the latest and greatest! 🚀

**Pull request merged**
