### PR TITLE
Fix AndroidLint by updating dependencies

### LINKED ISSUE #544: Reduce the size using the Android App Bundle
>Your app could be 60.7% smaller if you used the Android App Bundle. The APKs generated from the app bundle give your users smaller, more optimized downloads. 

>This calculation is based on your latest production release and the XXHDPI ARMv7 device configuration.

https://support.google.com/googleplay/android-developer/answer/9006925

### PR DESCRIPTION
**Pull request by beatbrot**
Connected to #544 and all other PRs

Updates recylcerview, appcompat and androidx.lifecycle-extensions so that android lint does not fail anymore

## To Do

- [ ] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by beatbrot** [comment]
Wooops this seems quite a bit more complicated than I thought...I guess I need a bit more time. If anyone is able to finish ahead of me, just commit/create a new PR since this issue is currently breaking the build

**Comment by beatbrot** [comment]
I have a feeling that like LockedPresenterTest is flaky and sometimes runs endlessly...I do not have hard evidence yet tough...

**Comment by beatbrot** [comment]
This PR currently depends on the approval of #573

**Comment by beatbrot** [comment]
I just want to add that this PR is still relevant as it fixes the tech debt introduced by suppressing the deprecation warning

**Comment by beatbrot** [comment]
@devinreams just wondering whether you could tell me why this PR was closed :)

**Comment by devinreams** [comment]
>tell me why this PR was closed :)

Whoops, the "closes/fixes" keywords in the description of PR 573 closed this upon merge. Sorry about that.

**Comment by beatbrot** [comment]
No problem :) It seems like it was my fault anyways :P

**Pull request merged**
